import AppKit

/// Processes new clipboard text; injected pasteboards keep checks away from the user's clipboard.
@MainActor
public final class ClipboardCleaner {
    private let pasteboard: NSPasteboard
    private var seenChange: Int
    private var replacementChange: Int?
    private var originalData: [NSPasteboard.PasteboardType: Data] = [:]

    public init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        seenChange = pasteboard.changeCount
    }

    public var canRestore: Bool {
        replacementChange == pasteboard.changeCount && !originalData.isEmpty
    }

    /// Do not process text already present on launch, when enabling the feature, or our own writes.
    public func ignoreCurrentChange() {
        seenChange = pasteboard.changeCount
    }

    public func poll(mergeLines: Bool = true, repairHyphens: Bool = false) -> (source: String, result: CleaningResult)? {
        let change = pasteboard.changeCount
        guard change != seenChange else { return nil }
        seenChange = change
        replacementChange = nil
        originalData = [:]

        guard let items = pasteboard.pasteboardItems, items.count == 1 else { return nil }
        let item = items[0]
        let excluded: Set<NSPasteboard.PasteboardType> = [
            .fileURL, .png, .tiff,
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
            NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        ]
        guard excluded.isDisjoint(with: item.types),
              let source = item.string(forType: .string),
              source.contains(where: \.isNewline) else { return nil }

        let result = TextCleaner.clean(source, mergeLines: mergeLines, repairHyphens: repairHyphens)
        guard !result.text.isEmpty, result.text != source else { return nil }
        var saved: [NSPasteboard.PasteboardType: Data] = [:]
        for type in item.types {
            if let data = item.data(forType: type) { saved[type] = data }
        }
        // Pasteboard data may be supplied lazily. Do not overwrite a newer copy while reading it.
        guard pasteboard.changeCount == change else { return nil }
        pasteboard.clearContents()
        guard pasteboard.setString(result.text, forType: .string) else {
            restoreRepresentations(saved)
            seenChange = pasteboard.changeCount
            return nil
        }
        seenChange = pasteboard.changeCount
        replacementChange = seenChange
        originalData = saved
        return (source, result)
    }

    @discardableResult
    public func restore() -> Bool {
        guard canRestore else { return false }
        let success = restoreRepresentations(originalData)
        seenChange = pasteboard.changeCount
        replacementChange = nil
        originalData = [:]
        return success
    }

    @discardableResult
    private func restoreRepresentations(_ data: [NSPasteboard.PasteboardType: Data]) -> Bool {
        let item = NSPasteboardItem()
        for (type, value) in data { item.setData(value, forType: type) }
        pasteboard.clearContents()
        return pasteboard.writeObjects([item])
    }
}
